name: Deploy Azure Infrastructure

on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
      - infra  # optional: run when pushing to the 'infra' branch

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy SQL Infrastructure
      run: |
        az deployment group create --resource-group abd-rg --template-file infrabicep/azsqldb.bicep --parameters dummySqlPassword='StrongP@ssword123'

    - name: Deploy Web App Infrastructure
      run: |
        az deployment group create --resource-group abd-rg --template-file infrabicep/webapp.bicep

    - name: Get SQL Connection String
      id: get-sql-conn
      run: |
        SERVER_NAME=abdsqlserver.database.windows.net
        DB_NAME=abdsqldb
        CONNECTION_STRING="Server=tcp:$SERVER_NAME,1433;Initial Catalog=$DB_NAME;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;"
        echo "sql_conn=$CONNECTION_STRING" >> $GITHUB_ENV

    - name: Set Connection String in Web App
      run: |
        az webapp config connection-string set --name abdregapp --resource-group abd-rg --settings "AZURE_SQL_CONNECTION_STRING=${{ env.sql_conn }}"