name: Deploy Azure Infrastructure and Node.js App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy SQL Infrastructure
      run: |
        az deployment group create --resource-group abd-rg --template-file infrabicep/azsqldb.bicep --parameters dummySqlPassword='StrongP@ssword123'

    - name: Deploy Web App Infrastructure
      run: |
        az deployment group create --resource-group abd-rg --template-file infrabicep/webapp.bicep

    - name: Get SQL Connection String
      id: get-sql-conn
      run: |
        SERVER_NAME=abdsqlserver.database.windows.net
        DB_NAME=abdsqldb
        CONNECTION_STRING="Server=tcp:$SERVER_NAME,1433;Initial Catalog=$DB_NAME;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;"
        echo "sql_conn=$CONNECTION_STRING" >> $GITHUB_ENV

    - name: Set Connection String in Web App
      run: |
        az webapp config appsettings set --name abdregapp --resource-group abd-rg --settings "AZURE_SQL_CONNECTION_STRING=Server=tcp:abdsqlserver.database.windows.net,1433;Initial Catalog=abdsqldb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: deploy-infra

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'abdregapp'
        package: ./release.zip
